### ISSUE TITLE
Update server database to store and retrieve secrets

### ISSUE THREAD

**Issue by marsella** [boltlabs-inc/key-mgmt#138]
In order to execute the key server 'store a secret' and 'retrieve a secret' flows, they need to be able to store an encrypted `Secret` and get it back out of the database.

- [x] Edit `User` model to hold `Encrypted<Secret>` instead of plain `Secret`. See if you can remove `Ser/De` bounds on `Secret.
- [x] Add store function
- [x] Add retrieve function
- [ ] Add test to make sure storing and retrieving doesn't work
- [ ] Add test to make sure you can only store one secret under a given key id (e.g. no overwriting)

**Comment by vidyaap** [comment]
Tasks relating to updating the DB models and functions were included in the [generate](https://github.com/boltlabs-inc/key-mgmt/pull/167) and [retrieve](https://github.com/boltlabs-inc/key-mgmt/pull/228) PRs.  Closing this issue because the testing tasks will be included in #216, after we can compare state.
