### ISSUE TITLE
Move SignatureScheme trait to crypto module

### ISSUE THREAD

**Issue by vidyaap** [boltlabs-inc/key-mgmt#43]
The `SignatureScheme` trait is a trait to indicate objects representing a signature scheme, and would hold signing operations common to different signature schemes. Right now, this trait is defined in the blockchain module, but some refactoring needs to be done to:
- [ ] move the trait definition to a crypto library
- [ ] define signing operations as trait methods
- [ ] ensure that structs representing specific signature schemes (e.g. the existing `ECDSA` struct in the blockchain module) implement this trait

**Comment by marsella** [comment]
The goals of this issue might change as we develop the crypto module. For example, we might 

An alternate approach to this: we may define a `Signer` trait over keys, rather than signature scheme objects (like `ECDSA`). In that case, this issue will have to find a way to link between types that implement the `SignatureScheme` trait and types that implement `Signer`. The `SignatureScheme` would indicate what _type_ of `Signer`s are appropriate for a blockchain, but not the actual keys used.

**Comment by indomitableSwan** [comment]
@marsella This issue can be closed as outdated, right?

**Comment by marsella** [comment]
I think if #252 ends up moving this trait out of the repo, then yes. Otherwise we should probably move it to the repo, and maybe just remove it.

**Comment by indomitableSwan** [comment]
Closing because we moved this trait out of the repo in #252. I think the correct time to decide where this trait should live and what it should do is when/if we re-integrate it.
