### ISSUE TITLE
Key Server: Support Storage of Arbitrary Client Data

### ISSUE THREAD

**Issue by LordQ1** [boltlabs-inc/key-mgmt#432]
**Background:** For other related projects, we may use the Key Server to store encrypted shards or to store arbitrary backup data (blobs). The blobs may already be encrypted by the client calling application prior to being sent to the Key Server. While we could utilize the arbitrary secrets functionality, it is not a perfect fit for the application. We might also be able to utilize the import functionality, but again, it is not a perfect fit. 

**Developer Note:** The developer assigned to this ticket should work closely with the Bolt cryptographers to select an appropriate course of action -- i.e., reuse an existing feature of the Key Server or implement a new feature. The requirements in this ticket are meant as a starting point, but should not impede the developer and cryptographers from selecting a better path forward. Please capture your notes after those discussions.

**Requirements:**

1. Provide a Key Server action that allows the client to store an arbitrary blob of data -- the arbitrary blob of data may have already been encrypted by the client (or may not)
1. Provide a Key Server action to retrieve an arbitrary blob of data
1. Write a log statement when either action (store or retrieve) is invoked that includes the account_id and blob_id (the blob_id might be the key_id -- TBD by the designer)
1. Capture audit events when a blob is stored or retrieved
1. The Key Server should encrypt the data blob before placing into the persistent storage of the Key Server
1. The Key Server should have a configurable maximum size of the blob to accept -- that is, if a blob exceeds the pre-configured maximum size, then an appropriate error should be returned and the request should be rejected

**Tasks:**

1. Work in conjunction with the Bolt cryptographers to determine whether we will use pre-existing functionality of the Key Server to satisfy these requirements or if we will add a new feature to the Key Server
1. Document your decisions and reasoning
1. If changes are required of the Key Server and/or LK Client, then document the enhancements/design
1. if changes are required, then this ticket should also track the implementation

**Comment by gatoWololo** [comment]
Here are some thoughts about this issue: Looking at our Lock-Keeper API there isn't any function which adequately matches what we need. The closets candidates in functionality are:
- `import_signing_key`: While it takes `key_material: Vec<u8>`, it looks like it will can fail if it cannot convert these bytes into a `SigningKey` with a specific expected format.

No other client API seems to quite fit what we want. However, the databases implementation of our stored secrets `StoredSecret` is pretty flexible and accommodates all the types of keys we would want. It would easy to add an extra endpoint to import/retrieve a Maestro shard. This wouldn't be very useful outside of Maestro, so we could generalize the endpoint to import/retrieve an arbitrary blob of data stored in the server as a secret (this might have been supported by the server once upon a time, but from what I can tell, there is not such endpoint right now).

There is also a question of whether the Server should encrypt the shards before storing them and decrypt them when retrieving them? My understanding is that the shards do not necessarily need to be encrypted before storing since a single shard by itself isn't useful to replicate the original secret).

**Comment by indomitableSwan** [comment]
> Here are some thoughts about this issue: Looking at our Lock-Keeper API there isn't any function which adequately matches what we need. The closets candidates in functionality are:
> 
> * `import_signing_key`: While it takes `key_material: Vec<u8>`, it looks like it will can fail if it cannot convert these bytes into a `SigningKey` with a specific expected format.
> 
> No other client API seems to quite fit what we want. However, the databases implementation of our stored secrets `StoredSecret` is pretty flexible and accommodates all the types of keys we would want. It would easy to add an extra endpoint to import/retrieve a Maestro shard. This wouldn't be very useful outside of Maestro, so we could generalize the endpoint to import/retrieve an arbitrary blob of data stored in the server as a secret (this might have been supported by the server once upon a time, but from what I can tell, there is not such endpoint right now).
> 

This sounds like we might want to implement a key server endpoint for e2e-encrypted storage functionality, as this is a functionality we will want to support in the future anyway. I'm not clear on the idea to generalize import/retrieve, though; I think this requires further discussion and thought.

> There is also a question of whether the Server should encrypt the shards before storing them and decrypt them when retrieving them? My understanding is that the shards do not necessarily need to be encrypted before storing since a single shard by itself isn't useful to replicate the original secret).

Yes, the server should encrypt all content received from the client, regardless of whether the content has already been encrypted by the client. 

For key records, the server ideally will have a storage functionality that uses per-record encryption keys to secure data. We may want this property for this "e2e-encrypted storage" functionality as well, in particular because then we can have just one key server storage functionality (and better ensure it's well-designed and implemented). This requires some cryptographic design work to specify server key management though; maybe there is a middle ground approach we can take for now here, where we set up the appropriate server-side APIs that anticipate this property.
