### ISSUE TITLE
Update scope of transaction approval requests

### ISSUE THREAD

**Issue by marsella** [boltlabs-inc/key-mgmt#47]
Right now, `TransactionApprovalRequest`s have a corresponding ID, which must be unique among requests. This is an immutable, read-only field on the TAR. 

In practice, we don't want the calling application (or transaction originating application) to be in charge of choosing the ID. Goals: avoid duplicated IDs, avoid potential attacks from similar/same IDs on different TARs. 

To close this issue 
- [ ] determine who the correct party is to choose the TAR (the mighty block app? our client code? the key servers via consensus? some combination of these?)
- [ ] define the flow for converting TARs into TARs with IDs assigned by the correct party (and telling the calling app what the ID is, probably).
- [ ] implement the solution

**Comment by indomitableSwan** [comment]
To reduce the attack surface and increase misuse resistance, choosing the TAR ID should be done by our client code as part of a transaction approval request session.

**Comment by vidyaap** [comment]
I changed the title of this issue because I think ID assignment is part of a larger scoping issue (scoping in the sense of “scope of a variable in a program”). A `TransactionApprovalRequest` needs to have an ID, and we want to be the ones to assign the ID.  In that case, it makes sense for this to be an internal type that we don’t expose to the calling application, and instead construct ourselves after asking for each of the fields as a separate parameter in the API functions.

It may be worth making a separate ID-less version of a TAR if it’s convenient for the calling app devs to group this data together.  But that seems unlikely since the calling app would already have its own way of storing the data we need to make a TAR.

**Comment by indomitableSwan** [comment]
Closing as an issue that was written prematurely. See https://github.com/boltlabs-inc/key-mgmt-spec/issues/136.
